import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/lib/auth";
import { MainNavigation } from "@/components/MainNavigation";
import { SignOutButton } from "@/components/SignOutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "bata comp",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {session && (
          <header className="bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex h-16 items-center justify-between">
                {/* App title with responsive text size */}
                <div className="flex items-center">
                  <code className="tracking-wide bg-black/[.05] dark:bg-white/[.06] px-2 py-1 rounded text-sm sm:text-md font-[family-name:var(--font-geist-mono)] font-semibold">
                    beta comp
                  </code>
                </div>

                {/* Navigation - now fully responsive */}
                <MainNavigation />

                {/* User actions with responsive text */}
                <div className="flex items-center gap-2 sm:gap-4">
                  <span className="text-xs text-muted-foreground hidden sm:block truncate max-w-[120px] lg:max-w-none">
                    {session.user.displayName}
                  </span>
                  <SignOutButton />
                </div>
              </div>
            </div>
          </header>
        )}

        <main className={session ? "pt-0" : ""}>{children}</main>
      </body>
    </html>
  );
}
